I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/level_1.rpy", line 648, in script
    "Sorry, I couldn’t help. You look so cute.":
ScriptError: could not find label 'apology2'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/level_1.rpy", line 648, in script
    "Sorry, I couldn’t help. You look so cute.":
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1992, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'apology2'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Social Engineering Game 1.0
Mon Jan 22 11:54:21 2024
